import {integer,sqliteTable,text,uniqueIndex,index} from "drizzle-orm/sqlite-core";
const timestamps={createdAt:integer("created_at",{mode:"timestamp"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()};
export const users=sqliteTable("users",{id:text("id").primaryKey(),email:text("email").notNull(),name:text("name").notNull(),role:text("role",{enum:["admin","leader","member"]}).notNull(),avatar:text("avatar"),active:integer("active",{mode:"boolean"}).notNull().default(true),...timestamps},t=>[uniqueIndex("idx_users_email").on(t.email)]);
export const projects=sqliteTable("projects",{id:text("id").primaryKey(),code:text("code").notNull(),name:text("name").notNull(),client:text("client").notNull(),description:text("description"),requirements:text("requirements"),internalNotes:text("internal_notes"),status:text("status").notNull(),priority:text("priority").notNull(),leaderId:text("leader_id").notNull().references(()=>users.id),deadline:integer("deadline",{mode:"timestamp"}),lastActivityAt:integer("last_activity_at",{mode:"timestamp"}),archivedAt:integer("archived_at",{mode:"timestamp"}),...timestamps},t=>[uniqueIndex("idx_projects_code").on(t.code),index("idx_projects_leader_status").on(t.leaderId,t.status)]);
export const projectMembers=sqliteTable("project_members",{id:text("id").primaryKey(),projectId:text("project_id").notNull().references(()=>projects.id),userId:text("user_id").notNull().references(()=>users.id),projectRole:text("project_role"),...timestamps},t=>[uniqueIndex("idx_project_members_unique").on(t.projectId,t.userId)]);
export const projectPhases=sqliteTable("project_phases",{id:text("id").primaryKey(),projectId:text("project_id").notNull().references(()=>projects.id),name:text("name").notNull(),position:integer("position").notNull(),state:text("state").notNull(),startedAt:integer("started_at",{mode:"timestamp"}),completedAt:integer("completed_at",{mode:"timestamp"}),...timestamps},t=>[index("idx_project_phases_order").on(t.projectId,t.position)]);
export const projectPhaseHistory=sqliteTable("project_phase_history",{id:text("id").primaryKey(),projectId:text("project_id").notNull().references(()=>projects.id),fromPhaseId:text("from_phase_id").references(()=>projectPhases.id),toPhaseId:text("to_phase_id").notNull().references(()=>projectPhases.id),requestedBy:text("requested_by").notNull().references(()=>users.id),approvedBy:text("approved_by").references(()=>users.id),state:text("state").notNull(),note:text("note"),...timestamps});
export const tasks=sqliteTable("tasks",{id:text("id").primaryKey(),projectId:text("project_id").notNull().references(()=>projects.id),phaseId:text("phase_id").references(()=>projectPhases.id),title:text("title").notNull(),description:text("description"),assigneeId:text("assignee_id").references(()=>users.id),createdBy:text("created_by").notNull().references(()=>users.id),reviewerId:text("reviewer_id").references(()=>users.id),status:text("status").notNull(),priority:text("priority").notNull(),dueAt:integer("due_at",{mode:"timestamp"}),blockedReason:text("blocked_reason"),blockedAt:integer("blocked_at",{mode:"timestamp"}),submittedAt:integer("submitted_at",{mode:"timestamp"}),reviewedAt:integer("reviewed_at",{mode:"timestamp"}),...timestamps},t=>[index("idx_tasks_assignee_status").on(t.assigneeId,t.status),index("idx_tasks_project_due").on(t.projectId,t.dueAt)]);
export const taskChecklists=sqliteTable("task_checklists",{id:text("id").primaryKey(),taskId:text("task_id").notNull().references(()=>tasks.id),label:text("label").notNull(),position:integer("position").notNull(),completed:integer("completed",{mode:"boolean"}).notNull().default(false),completedBy:text("completed_by").references(()=>users.id),completedAt:integer("completed_at",{mode:"timestamp"}),...timestamps});
export const taskComments=sqliteTable("task_comments",{id:text("id").primaryKey(),taskId:text("task_id").notNull().references(()=>tasks.id),authorId:text("author_id").notNull().references(()=>users.id),body:text("body").notNull(),...timestamps});
export const revisions=sqliteTable("revisions",{id:text("id").primaryKey(),projectId:text("project_id").notNull().references(()=>projects.id),phaseId:text("phase_id").notNull().references(()=>projectPhases.id),number:integer("number").notNull(),notes:text("notes"),state:text("state").notNull(),submittedBy:text("submitted_by").references(()=>users.id),submittedAt:integer("submitted_at",{mode:"timestamp"}),reviewedBy:text("reviewed_by").references(()=>users.id),reviewedAt:integer("reviewed_at",{mode:"timestamp"}),reviewOutcome:text("review_outcome"),...timestamps},t=>[uniqueIndex("idx_revisions_cycle").on(t.phaseId,t.number)]);
export const revisionComments=sqliteTable("revision_comments",{id:text("id").primaryKey(),revisionId:text("revision_id").notNull().references(()=>revisions.id),authorId:text("author_id").notNull().references(()=>users.id),body:text("body").notNull(),...timestamps});
export const dailyUpdates=sqliteTable("daily_updates",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>users.id),projectId:text("project_id").references(()=>projects.id),summary:text("summary").notNull(),blockers:text("blockers"),nextSteps:text("next_steps"),updateDate:text("update_date").notNull(),...timestamps},t=>[index("idx_daily_updates_user_date").on(t.userId,t.updateDate)]);
export const notifications=sqliteTable("notifications",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>users.id),type:text("type").notNull(),severity:text("severity").notNull(),title:text("title").notNull(),body:text("body"),entityType:text("entity_type"),entityId:text("entity_id"),readAt:integer("read_at",{mode:"timestamp"}),...timestamps},t=>[index("idx_notifications_user_read").on(t.userId,t.readAt)]);
export const activityLogs=sqliteTable("activity_logs",{id:text("id").primaryKey(),actorId:text("actor_id").references(()=>users.id),projectId:text("project_id").references(()=>projects.id),action:text("action").notNull(),entityType:text("entity_type").notNull(),entityId:text("entity_id"),metadata:text("metadata",{mode:"json"}),createdAt:integer("created_at",{mode:"timestamp"}).notNull()},t=>[index("idx_activity_project_created").on(t.projectId,t.createdAt)]);

